<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div>
        <span>
            <input style="width:80%" id="smartVoucher" type="text" title="<?php echo $this->__('Smart Voucher') ?>" name="payment[smart_voucher]" value="<?php echo $this->htmlEscape($this->getInfoData('smart_voucher')) ?>" />
        </span>
        <span class="messageVoucher" style="display:none;color:red;font-weight: normal"> !Please enter data</span>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>

