

<div id="header-image">
    <img class="d-block width-img-header height-img-header" src="" alt="First slide">
    <div class="img-header-container">
        <div class="text-up-position">
            <div class="text-centered text-uppercase text-up">Shop</div>
        </div>
        <div class="text-down-position">
            <div class="text-centered text-down">
                <ul class="clear-list-style">
                    <li><a href="">Home</a></li>/
                    <li><a href="">Shop</a></li>/
                    <li><p>Vesper Floor Lamp<p></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Begin content -->
<section id="content">
    <div class="container" id="inner-content">
        <div class="row">
            <div class="col-md-5"></div>
            <div class="col-md-7"></div>
        </div>
    </div>
    <div id="description-content" class="container">
        <div class="container" id="inner-content">
            <div class="row">
                <div class="col-md-5"></div>
                <div class="col-md-7"></div>
            </div>
        </div>
        <div id="description-content" class="container">
            <div class="info_tab">
                <ul class="nav nav-tabs">
                    <li class="active"><a data-toggle="tab" href="#description" aria-expanded="true">Description</a></li>
                    <li class=""><a data-toggle="tab" href="#additional" aria-expanded="false">Additional Information</a></li>
                    <li class=""><a data-toggle="tab" href="#reviews" aria-expanded="false">Reviews (0)</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade active in" id="description">
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. Sed dapibus iaculis massa ac accumsan. Donec venenatis, mi vitae aliquam molestie, orci justo lobortis mauris, in consequat massa nisi ut odio.</p>
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. In hac habitasse platea dictumst. Suspendisse potenti. Donec cursus metus nulla, quis lobortis erat ultricies sed</p>
                    </div>
                    <div class="tab-pane fade" id="additional">
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. Sed dapibus iaculis massa ac accumsan. Donec venenatis, mi vitae aliquam molestie, orci justo lobortis mauris, in consequat massa nisi ut odio.</p>
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. In hac habitasse platea dictumst. Suspendisse potenti. Donec cursus metus nulla, quis lobortis erat ultricies sed</p>
                    </div>
                    <div class="tab-pane fade" id="reviews">
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. Sed dapibus iaculis massa ac accumsan. Donec venenatis, mi vitae aliquam molestie, orci justo lobortis mauris, in consequat massa nisi ut odio.</p>
                        <p>Aenean a accumsan sem. In faucibus molestie purus non consequat. Cras leo turpis, varius in ultricies id, accumsan id dui. Sed elit nisi, porta a nisl a, dignissim porta enim. Aliquam facilisis fringilla justo, sed efficitur purus posuere porttitor. Suspendisse vulputate, nulla in sodales elementum, orci erat ullamcorper dui, ac sollicitudin metus leo ac ligula. In hac habitasse platea dictumst. Suspendisse potenti. Donec cursus metus nulla, quis lobortis erat ultricies sed</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End content -->

<!-- Begin Our Products -->
<section id="our-products">

</section>
<!-- End Our Products -->